import js from '@eslint/js';

export default [
  {
    ignores: ['dist/**/*', 'node_modules/**/*', 'android/**/*', 'coverage/**/*'],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        localStorage: 'readonly',
        console: 'readonly',
        URL: 'readonly',
        fetch: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        navigator: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        atob: 'readonly',
        Blob: 'readonly',
        Uint8Array: 'readonly',
        ArrayBuffer: 'readonly',
        FileReader: 'readonly',
        Image: 'readonly',
        Worker: 'readonly',
        indexedDB: 'readonly',
        location: 'readonly',
        Promise: 'readonly',
        Math: 'readonly',
        Response: 'readonly',
        caches: 'readonly',
        self: 'readonly',
        postMessage: 'readonly',
        importScripts: 'readonly',
        module: 'readonly',
        process: 'readonly',
        exports: 'writable',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-redeclare': 'off',
      'no-console': ['warn', { allow: ['error', 'warn', 'info'] }],
      'no-debugger': 'error',
      'eqeqeq': ['error', 'always'],
      'curly': ['error', 'all'],
    },
  },
];
