import { ICONS } from "../ui/icons.js";

export const toolsList = [
  {
    id: 'merge',
    title: 'Merge PDF',
    icon: ICONS.merge,
    desc: 'Combine multiple PDFs into one document',
    cat: 'organize',
    keywords: 'merge pdf, combine pdf, join pdf, append pdf',
  },
  {
    id: 'split',
    title: 'Split PDF',
    icon: ICONS.split,
    desc: 'Extract pages from your PDF into separate files',
    cat: 'organize',
    keywords: 'split pdf, extract pages, separate pdf, divide pdf',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    icon: ICONS.compress,
    desc: 'Reduce file size without losing quality',
    cat: 'optimize',
    keywords: 'compress pdf, shrink pdf, reduce pdf size, optimize pdf',
  },
  {
    id: 'rotate',
    title: 'Rotate PDF',
    icon: ICONS.rotate,
    desc: 'Rotate pages to correct orientation',
    cat: 'edit',
    keywords: 'rotate pdf, flip pdf, turn pdf, orientation',
  },
  {
    id: 'reorder',
    title: 'Reorder PDF',
    icon: ICONS.reorder,
    desc: 'Change the order of PDF pages',
    cat: 'organize',
    keywords: 'reorder pdf, rearrange pages, sort pdf pages',
  },
  {
    id: 'delete-pages',
    title: 'Delete Pages',
    icon: ICONS.delete_pages,
    desc: 'Remove unwanted pages from your PDF',
    cat: 'organize',
    keywords: 'delete pdf pages, remove pages, pdf page remover',
  },
  {
    id: 'extract-pages',
    title: 'Extract Pages',
    icon: ICONS.extract_pages,
    desc: 'Get specific pages as a new PDF document',
    cat: 'organize',
    keywords: 'extract pdf pages, save pages, pdf page extractor',
  },
  {
    id: 'image-to-pdf',
    title: 'Image to PDF',
    icon: ICONS.image_to_pdf,
    desc: 'Convert JPG, PNG, WEBP images to PDF',
    cat: 'convert',
    keywords: 'image to pdf, jpg to pdf, png to pdf, photo to pdf',
  },
  {
    id: 'pdf-to-image',
    title: 'PDF to Image',
    icon: ICONS.pdf_to_image,
    desc: 'Convert PDF pages to JPG or PNG images',
    cat: 'convert',
    keywords: 'pdf to image, pdf to jpg, pdf to png, export pdf images',
  },
  {
    id: 'protect',
    title: 'Protect PDF',
    icon: ICONS.protect,
    desc: 'Add password protection to your PDF document',
    cat: 'security',
    keywords: 'password protect pdf, encrypt pdf, secure pdf, lock pdf',
  },
  {
    id: 'unlock',
    title: 'Unlock PDF',
    icon: ICONS.unlock,
    desc: 'Remove password protection from PDF',
    cat: 'security',
    keywords: 'unlock pdf, remove password, decrypt pdf, pdf password remover',
  },
  {
    id: 'watermark',
    title: 'Watermark',
    icon: ICONS.watermark,
    desc: 'Stamp text on your PDF pages',
    cat: 'edit',
    keywords: 'watermark pdf, add watermark, text stamp, pdf stamp',
  },
  {
    id: 'add-page-numbers',
    title: 'Page Numbers',
    icon: ICONS.add_page_numbers,
    desc: 'Insert page numbers into your PDF',
    cat: 'edit',
    keywords: 'add page numbers, number pages, pdf pagination',
  },
  {
    id: 'add-blank-page',
    title: 'Add Blank Page',
    icon: ICONS.add_blank_page,
    desc: 'Insert blank pages anywhere in your PDF',
    cat: 'edit',
    keywords: 'add blank page, insert page, pdf page inserter',
  },
  {
    id: 'crop-resize',
    title: 'Crop & Resize',
    icon: ICONS.crop_resize,
    desc: 'Adjust margins and page dimensions',
    cat: 'optimize',
    keywords: 'crop pdf, resize pdf, adjust margins, pdf dimensions',
  },
];

export const toolCategories = [
  { id: 'all', label: 'All Tools' },
  { id: 'organize', label: 'Organize' },
  { id: 'optimize', label: 'Optimize' },
  { id: 'edit', label: 'Edit' },
  { id: 'convert', label: 'Convert' },
  { id: 'security', label: 'Security' },
];
